### ISSUE TITLE
Was your experiment successful?

### ISSUE THREAD

**Issue by mbdash** [CODEJIN/AutoVC#1]
Was your experiment successful?

I am looking into voice style transfer where I could finetune the the model for a single target voice only.

**Comment by CODEJIN** [comment]
Hi,

Unfortunately, it was not perfect. When I tried, I could observed `male to female transfer` and `female to male transfer`. However, transfer between the same sex were limited.

I think that [SpeechSplit](https://github.com/CODEJIN/SPEECHSPLIT) which has similar concept is partially better than AutoVC.

And, if you are okay, please consider [Pitchtron](https://github.com/hash2430/pitchtron) also.

**Comment by mbdash** [comment]
Thank you for your quick response and the links,
I will also share with you links I have found while researching repos tonight.

I have found this below:
https://github.com/jxzhanggg/nonparaSeq2seqVC_code

I will be paying attention to the results of the INTERSPEECH 2020 competition:
http://vc-challenge.org/


Some VCC20 competitors are already starting to publish their results on GitHub:
https://github.com/bigpon/vcc20_baseline_cyclevae

Another interesting repo:
https://github.com/mindslab-ai/cotatron

**Comment by CODEJIN** [comment]
Got it. Thanks!
